### ISSUE TITLE
Crop Image tool not working with pyRevit version 4.7.4

### ISSUE THREAD

**Issue by kenmarcus10** [gtalarico/pyrevitplus#19]
Hi,

I am having an issue with the Crop Image tool on Pyrevit Plus. Here is the version info: 4.7.4:277:2020.2.

I follow the steps required for the tool to work in the previous version but I am getting different error messages when I try to run:

**this is one error:**

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 171, in <module>
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 79, in crop_image
Exception: Image Source path not found: 

Script Executor Traceback:
IronPython.Runtime.Exceptions.PythonException: Image Source path not found: 
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**this is a second error:**

[ERROR] Error in Transaction Context: has rolled back. 

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 182, in <module>
Exception: OutOfRange
Parameter name: options.Resolution

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: OutOfRange
Parameter name: options.Resolution
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**here is a third error:**

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 171, in <module>
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 79, in crop_image
Exception: Image Source path not found: 

Script Executor Traceback:
IronPython.Runtime.Exceptions.PythonException: Image Source path not found: 
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
I have tried in multiple files, Floor plan, drafting and rendering views. None are working.

I have tried this on other machines and am getting the same results. I have tried all of the other pyRevitPlus tools and those are working fine. It appears to only be happening with the crop image tool

Is it possible that the process has changed? Draw a filled region. Select the image and filled image, choose the crop image tool?

Also, what is the process to do multiple crops on the same image at once? I have tried to follow the video example but can not replicate it.

thanks for your help.

Ken Marcus

**Comment by gtalarico** [comment]
Go to the manage images dialog and make sure the target image is linked properly (source image not found).

I don't think it's possible to do multiple crops at once

**Comment by kenmarcus10** [comment]
thanks I will check that.

I was looking at the video on your GitHub page for the crop image tool and it shows you adding multiple fill regions on one image and cropping it multiple times. Am I looking at the wrong video. Here is the link to the video I am mentioning. https://vimeo.com/180429233

<https://vimeo.com/180429233>
Thanks,
Ken Marcus
Revit Integration Consultant
____________________________________________________________
RFI Consultants Inc. l 638 Viona Ave. l Oakland, CA 94610
Phone: 415.979.0678<tel://Phone:415.979.0678> l www.rficonsultants.com<http://www.rficonsultants.com/>

* RFI asks you to consider the environment before you print this email.


On January 31, 2020 at 7:23:08 PM, Gui Talarico (notifications@github.com<mailto:notifications@github.com>) wrote:

Go to the manage images dialog and make sure the target image is linked properly (source image not found).

I don't think it's possible to do multiple crops at once

**Comment by kenmarcus10** [comment]
Awesome, thanks for the quick response. Didn’t realize it needed to be worked linked in with a path. I was trying to use images that were already in one of the sample files.



Thanks,
Ken Marcus
Revit Integration Consultant
____________________________________________________________
RFI Consultants Inc. l 638 Viona Ave. l Oakland, CA 94610
Phone: 415.979.0678<tel://Phone:415.979.0678> l www.rficonsultants.com<http://www.rficonsultants.com/>

* RFI asks you to consider the environment before you print this email.


On January 31, 2020 at 7:23:08 PM, Gui Talarico (notifications@github.com<mailto:notifications@github.com>) wrote:

Go to the manage images dialog and make sure the target image is linked properly (source image not found).

I don't think it's possible to do multiple crops at once

**Comment by gtalarico** [comment]
> I was trying to use images that were already in one of the sample files.
Script needs to find original image to perform crop as that's the only way to access the image.

You can do multiple crops, just not all at once. You have to re-run the tool for each selection srt

**Comment by gtalarico** [comment]
closing this as there are no issues here. feel free to ask follow up questiokns

**Comment by kenmarcus10** [comment]
Gui,

Following up on the same issue. I followed your steps and it works fine in 2019 but I get the following error in 2020 using the exact same image and process.  Any suggestions?


[ERROR] Error in Transaction Context: has rolled back.

IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 182, in <module>
Exception: OutOfRange
Parameter name: options.Resolution


Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: OutOfRange
Parameter name: options.Resolution
at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)


Thanks,
Ken Marcus
Revit Integration Consultant
____________________________________________________________
RFI Consultants Inc. l 638 Viona Ave. l Oakland, CA 94610
Phone: 415.979.0678<tel://Phone:415.979.0678> l www.rficonsultants.com<http://www.rficonsultants.com/>

* RFI asks you to consider the environment before you print this email.


On February 2, 2020 at 7:44:00 PM, Gui Talarico (notifications@github.com<mailto:notifications@github.com>) wrote:

closing this as there are no issues here. feel free to ask follow up questiokns

**Comment by nathanstolarz** [comment]
Gui,

I also am unable to great the crop tool to work in Revit 2020.  Any further suggestions at all?

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\nathan\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 171, in <module>
 File "C:\Users\nathan\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 80, in crop_image
ValueError: Parameter is not valid.


Script Executor Traceback:
System.ArgumentException: Parameter is not valid.
 at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by gtalarico** [comment]
sorry guys I haven't been using this in a while at this time won't be able to help as I don't have revit setup.

**Comment by kenmarcus10** [comment]
Thanks for get back to me and letting me know. Is there anything I can assist with helping out since I do have Revit setup? I would be happy to work with you and help you get the info you need to fix it.

I have several clients that I have shown you addin to and they love it so it would be great if we could get it working

Let me know

Thanks,
Ken Marcus
415.979.0678
Revit integration consultant
Www.rficonsultants.com
On Feb 5, 2020, 9:43 PM -0800, Gui Talarico <notifications@github.com>, wrote:

sorry guys I haven't been using this in a while at this time won't be able to help as I don't have revit setup.

**Comment by sims1216** [comment]
@gtalarico Hi Gui! I hope you're well. I discovered this thread while surfing around github. I had a chance to update the Crop Image tool and make it compatible with Revit 2020. I can share it if you want, since it's originated from your code! (Unfortunately, it's not downward compatible.)
