### ISSUE TITLE
Revit 2021 Crop image not working

### ISSUE THREAD

**Issue by MarcelP102** [gtalarico/pyrevitplus#24]
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\marce\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\Image.panel\Crop Image.pushbutton\script.py", line 174, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'ImageImportOptions'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'ImageImportOptions'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by gtalarico** [comment]
Sorry I am no longer maintaining this. It's probably a revit 2021 breaking
api change
- Gui Talarico
